# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pcb_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pcb_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11pcb_service.proto\x12\x03pcb\x1a\x1bgoogle/protobuf/empty.proto\"\x0b\n\tHeartbeat\"\x1d\n\rRemoveProfile\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x8d\x01\n\rMosfetControl\x12\x10\n\x08mosfet_1\x18\x01 \x01(\x08\x12\x10\n\x08mosfet_2\x18\x02 \x01(\x08\x12\x10\n\x08mosfet_3\x18\x03 \x01(\x08\x12\x10\n\x08mosfet_4\x18\x04 \x01(\x08\x12\x10\n\x08mosfet_5\x18\x05 \x01(\x08\x12\x10\n\x08mosfet_6\x18\x06 \x01(\x08\x12\x10\n\x08mosfet_7\x18\x07 \x01(\x08\"2\n\x0cServoControl\x12\r\n\x05\x61ngle\x18\x01 \x01(\r\x12\x13\n\x0braise_lower\x18\x02 \x01(\x05\"\x1d\n\x0c\x42ilgeControl\x12\r\n\x05speed\x18\x01 \x01(\x05\"\x11\n\x0fShutdownCommand\"\xc5\x01\n\rClientMessage\x12#\n\theartbeat\x18\x01 \x01(\x0b\x32\x0e.pcb.HeartbeatH\x00\x12,\n\x0emosfet_control\x18\x02 \x01(\x0b\x32\x12.pcb.MosfetControlH\x00\x12*\n\rservo_control\x18\x03 \x01(\x0b\x32\x11.pcb.ServoControlH\x00\x12*\n\rbilge_control\x18\x04 \x01(\x0b\x32\x11.pcb.BilgeControlH\x00\x42\t\n\x07payload2E\n\nPCBService\x12\x37\n\x07Session\x12\x12.pcb.ClientMessage\x1a\x16.google.protobuf.Empty(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pcb_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEARTBEAT']._serialized_start=55
  _globals['_HEARTBEAT']._serialized_end=66
  _globals['_REMOVEPROFILE']._serialized_start=68
  _globals['_REMOVEPROFILE']._serialized_end=97
  _globals['_MOSFETCONTROL']._serialized_start=100
  _globals['_MOSFETCONTROL']._serialized_end=241
  _globals['_SERVOCONTROL']._serialized_start=243
  _globals['_SERVOCONTROL']._serialized_end=293
  _globals['_BILGECONTROL']._serialized_start=295
  _globals['_BILGECONTROL']._serialized_end=324
  _globals['_SHUTDOWNCOMMAND']._serialized_start=326
  _globals['_SHUTDOWNCOMMAND']._serialized_end=343
  _globals['_CLIENTMESSAGE']._serialized_start=346
  _globals['_CLIENTMESSAGE']._serialized_end=543
  _globals['_PCBSERVICE']._serialized_start=545
  _globals['_PCBSERVICE']._serialized_end=614
# @@protoc_insertion_point(module_scope)
